New route/get next katathon
GiacomoSorbi/katathon pull request #37
Opened 2018-10-09 00:40 UTC by AnnaVih

The new route will return the closest event object.

2018-10-09 12:36 UTC, webtechalex requested changes

2018-10-09 12:36 UTC, webtechalex commented on server/controllers/index.js
>          if(name) kata.name = name
Can we use `Object.assign()` here to merge available properties in to the kata object?
(You will need to create a new object from the `req.body` with the destructured properties first)
Then you can transform the `if` into a ternary:
`return (kata.kataId == kataId) ? Object.assign({}, kata, bodyCopy) : kata`

2018-10-09 12:36 UTC, webtechalex commented on server/controllers/index.js
> +    const katathons = await Katathon.find({ completed: false }).sort({ date_created: -1 })
Why `dateCreated: -1`?

2018-10-09 12:36 UTC, webtechalex commented on server/controllers/index.js
> +        result: '404',
I think `result` should be: `Not Found` for a 404 status

2018-10-09 12:36 UTC, webtechalex commented on server/controllers/index.js
> +      result: 'failed',
Maybe overly picky, but capitalise `Failed` for consistency with `Success` and `Not Found`, suggested above.

2018-10-09 22:32 UTC, AnnaVih commented
@webtechalex Amended!)

2018-10-27 12:28 UTC, webtechalex approved these changes

2018-10-27 12:28 UTC, merged