Completes leader board route
GiacomoSorbi/katathon pull request #39
Opened 2018-10-31 17:30 UTC by jakec-github

In this code I leave the message property of the success json as a blank string. Not sure if that is what you guys are after

2018-10-31 19:51 UTC, AnnaVih approved these changes
Looks fine to me))

2018-11-02 21:28 UTC, webtechalex requested changes

2018-11-02 21:28 UTC, webtechalex commented on server/controllers/index.js
> +export const leaderBoard = async (req, res) => {
should this have some verb in the name like the other controllers? `getLeaderboard`, maybe? In what context will this function be used?

2018-11-03 14:22 UTC, webtechalex approved these changes

2018-11-03 14:22 UTC, webtechalex commented
LGTM. Merging...

2018-11-03 14:22 UTC, merged